# Generated by Django 3.2.13 on 2022-06-05 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackItemComponents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=150)),
                ('site_type', models.CharField(choices=[('SK', 'SKROUTZ'), ('BG', 'BANGGOOD'), ('LR', 'Leroy Merlin'), ('PR', 'Praktiker')], default='SK', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TrackItemHeader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
